CREATE TABLE IF NOT EXISTS "ACTORS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"NAME"	TEXT,
	"DESCRIPTION"	TEXT,
	"ARMORCLASS"	INTEGER,
	"HITPOINTS"	INTEGER,
	"AVERAGESAVE"	NUMERIC,
	"TOHITBONUS"	INTEGER,
	"SAVEDC"	INTEGER,
	"BASEDPR"	NUMERIC,
	"MAXDPR"	NUMERIC,
	"JSONSTATS"	BLOB,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "DICE" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"DESCRIPTION"	TEXT,
	"AVERAGE"	NUMERIC,
	"MINVALUE"	NUMERIC,
	"MAXVALUE"	NUMERIC,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "SHAPES" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"DESCRIPTION"	TEXT,
	"DIMENSIONSX"	NUMERIC,
	"DIMENSIONSY"	NUMERIC,
	"DIMENSIONSZ"	NUMERIC,
	"AREA"	NUMERIC,
	"TARGETRATE"	NUMERIC,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "ITEMS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"NAME"	TEXT,
	"DESCRIPTION"	TEXT,
	"MAXUSES"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "EFFECTS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"NAME"	TEXT,
	"DESCRIPTION"	TEXT,
	"DELIVERYTYPE"	INTEGER,
	"EFFECTTYPE"	INTEGER,
	"NUMACTIVATIONS"	INTEGER,
	"NUMTARGETS"	INTEGER,
	"FORMULA"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("DELIVERYTYPE") REFERENCES "DELIVERYTYPES"("ID"),
	FOREIGN KEY("EFFECTTYPE") REFERENCES "EFFECTTYPES"("ID")
);

CREATE TABLE IF NOT EXISTS "DELIVERYTYPES" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"DESCRIPTION"	TEXT,
	"SHAPETYPE"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("SHAPETYPE") REFERENCES "SHAPES"("ID")
);

CREATE TABLE IF NOT EXISTS "EFFECTTYPES" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"DESCRIPTION"	NUMERIC,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "RACTORSITEMS" (
	"ACTORID"	INTEGER NOT NULL,
	"ITEMID"	INTEGER NOT NULL,
	PRIMARY KEY("ACTORID","ITEMID"),
	FOREIGN KEY("ACTORID") REFERENCES "ACTORS"("ID"),
	FOREIGN KEY("ITEMID") REFERENCES "ITEMS"("ID")
);
CREATE TABLE IF NOT EXISTS "RITEMSEFFECTS" (
	"ITEMID"	INTEGER NOT NULL,
	"EFFECTID"	INTEGER NOT NULL,
	PRIMARY KEY("ITEMID","EFFECTID"),
	FOREIGN KEY("EFFECTID") REFERENCES "EFFECTS"("ID"),
	FOREIGN KEY("ITEMID") REFERENCES "ITEMS"("ID")
);

INSERT INTO DICE (DESCRIPTION, AVERAGE, MINVALUE, MAXVALUE)
VALUES ("d4", 2.5, 1, 4);

INSERT INTO DICE (DESCRIPTION, AVERAGE, MINVALUE, MAXVALUE)
VALUES ("d6", 3.5, 1, 6);

INSERT INTO DICE (DESCRIPTION, AVERAGE, MINVALUE, MAXVALUE)
VALUES ("d8", 4.5, 1, 8);

INSERT INTO DICE (DESCRIPTION, AVERAGE, MINVALUE, MAXVALUE)
VALUES ("d10", 5.5, 1, 10);

INSERT INTO DICE (DESCRIPTION, AVERAGE, MINVALUE, MAXVALUE)
VALUES ("d12", 6.5, 1, 12);

INSERT INTO DICE (DESCRIPTION, AVERAGE, MINVALUE, MAXVALUE)
VALUES ("d20", 10.5, 1, 20);

INSERT INTO DICE (DESCRIPTION, AVERAGE, MINVALUE, MAXVALUE)
VALUES ("d100", 50.5, 1, 100);
